<?php echo $this->flash(); ?>
<div class="row justify-content-md-center">
    <div class="col-md-6  col-xs-12">

        <div class="card">
            <div class="card-body">

                <?php echo $this->form()->openTag($form) ?>
                <legend><?php echo $this->translate('Password Recovery'); ?></legend>
                <!--<h4>Por favor completa el siguiente formulario.</h4>-->

                <?php $element = $form->get('email'); ?>
                <div class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">


                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <?php
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat('<span class="help-block">')
                            ->setMessageSeparatorString('</span><span class="help-block">')
                            ->setMessageCloseString('</span>')
                            ->render($element);
                        ?>

                    <?php endif; ?>

                </div>

                <div>

                    <?php echo $this->formElement($form->get('submit')); ?>

                </div>
                <?php echo $this->form()->closeTag($form); ?>

            </div>
        </div>
    </div>
</div>
