<?php $this->flashCurrent(); ?>

<div class="card">
    <div class="card-header card-header-icon" data-background-color="rose">
        <i class="material-icons">assignment</i>
    </div>
    <div class="card-content">
        <?php if ($this->grid->getOptions()->getTitle()): ?>
            <h4 class="card-title"><?php echo $this->grid->get_title_form(); ?></h4>
        <?php endif; ?>
        <div class="clearfix"></div>

        <div>

            <?php
            $form = $this->grid->getCrudForm();
            $formConfig = $this->grid->getOptions()->getFormConfig();

            $form->get('submit')->setAttribute('value', 'Guardar')
                ->setAttribute('class', 'pull-right btn btn-primary')
                ->setAttribute('style', 'margin-left: 2px');

            $form->add(array(
                'name' => 'cancel',
                'type' => 'Zend\Form\Element\Button',
                'attributes' => array(
                    'value' => "Cancelar",
                    'class' => 'pull-right btn btn-default',
                    'onclick' => 'window.location.href="' . $this->url($this->route, array(), array('query' => $this->routeParams), true) . '"',
                ),
                'options' => array(
                    'label' => 'Cancelar',
                )
            ));
            ?>
            <?php
            echo $this->renderForm($form, $formConfig->getStyle(), $formConfig->getColumns(), $formConfig->getGroups());
            ?>
        </div>
    </div>

</div>