<?php $this->flashCurrent(); ?>
<div id="<?php echo $this->grid->getId(); ?>">

    <div class="card">
        <div class="card-header card-header-icon" data-background-color="rose">
            <i class="material-icons">assignment</i>
        </div>
        <div class="card-content">
            <?php if ($this->grid->getOptions()->getTitle()): ?>
                <h4 class="card-title"><?php echo $this->grid->getOptions()->getTitle(); ?></h4>
            <?php endif; ?>




            <?php echo $this->partial($this->partialExports, array("grid" => $this->grid)); ?>

            <?php /*if ($this->grid->getOptions()->getCrudConfig()->getAdd()->getEnable()): */?><!--
                <a <?php /*echo $this->grid->getCrudColumn()->getAdd()["action"]; */?>
                        class="btn pull-right btnCustom" style="margin-left:2px;">
                    <i class="fa fa-plus-circle fa-lg"></i> <?php /*echo $this->grid->getCrudColumn()->getAdd()["value"]; */?>
                </a>
            --><?php /*endif; */?>
            <?php if ($this->grid->getOptions()->getMultiSearchConfig()->getEnable()): ?>
                <?php echo $this->partial($this->partialSearch, array("grid" => $this->grid)); ?>
            <?php endif; ?>


            <?php if ($this->grid->getOptions()->getMultiFilterConfig()->getEnable()): ?>
                <?php echo $this->partial($this->partialFilter, array("grid" => $this->grid)); ?>
            <?php endif; ?>
            <div class="clearfix"></div>
            <div class="table-responsive">

                <table class="table table-striped table-no-bordered table-hover dataTable dtr-inline <?php echo $this->grid->getTableClass(); ?>">
                    <!--HEADER-->
                    <thead>
                    <tr>
                        <?php foreach ($this->grid->getColumns() as $column): ?>
                            <?php if (!$column->getHidden()): ?>

                                <?php if ($column->getType() != "extra" && $column->getType() != "crud"): ?>

                                    <!--SORT-->
                                    <?php if ($this->grid->getSort() && $this->grid->getSort()->getBy() == $column->getName()): ?>
                                        <?php if ($this->grid->getSort()->getDirection() == "DESC"): ?>
                                            <th class="sorting_desc">
                                            <a class=""
                                               href="<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "ASC") + $this->routeParams), true); ?>">

                                                <?php echo $this->translate((string)$column); ?>

                                            </a>

                                        <?php elseif ($this->grid->getSort()->getDirection() == "ASC"): ?>
                                            <th class="sorting_asc">
                                            <a class=""
                                               href="<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>">
                                                <?php echo $this->translate((string)$column); ?>
                                            </a>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <th class="sorting">
                                        <a class=""
                                           href="<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>">
                                            <?php echo $this->translate((string)$column); ?>
                                        </a>
                                    <?php endif; ?>

                                <?php else: ?>
                                    <th class=" <?php echo $column->getThClass(); ?>">
                                    <a><?php echo $this->translate((string)$column); ?></a>

                                <?php endif; ?>
                                </th>

                            <?php endif; ?>
                        <?php endforeach; ?>

                    </tr>
                    </thead>
                    <tbody>
                    <!--BODY-->
                    <?php if ($this->grid->getRow() && count($this->grid->getRow())): ?>
                        <?php foreach ($this->grid->getRow() as $data): ?>
                            <tr>
                                <?php foreach ($this->grid->getColumns() as $column): ?>
                                    <?php if (!$column->getHidden()): ?>
                                        <td class="<?php echo $column->getTdClass(); ?>">
                                            <?php //TODO - echo $column->getHtmlBegin(); ?>

                                            <?php echo $this->GridField($column, $data); ?>

                                            <?php //TODO - echo $column->getHtmlEnd(); ?>

                                        </td>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    </tbody>
                </table>
            </div>

            <?php
            echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', $this->partialPagination, array("routeParams" => $this->routeParams,
                'route' => $this->route));
            ?>


            <?php echo $this->GridCrud($this->grid->getId()); ?>
            <!--MODAL-->
            <?php echo $this->partial($this->partialModal, array("grid" => $this->grid)); ?>


        </div>
    </div>
</div>