<?php $record = $this->grid->getRecordDetail(); ?>

    <div class="card">
        <div class="card-header card-header-icon" data-background-color="rose">
            <i class="material-icons">assignment</i>
        </div>
        <div class="card-content">
            <?php if ($this->grid->getOptions()->getTitle()): ?>
                <h4 class="card-title">Detalle</h4>
            <?php endif; ?>
            <div class="clearfix"></div>

            <a class="btn btn-default btn-xs pull-right"
               href="<?php echo $this->url($this->route, array(), array('query' => $this->routeParams), true); ?>">
                <?php echo $this->translate('Listar'); ?>
            </a>
            <?php if ($this->grid->getOptions()->getCrudConfig()->getEdit()->getEnable()): ?>
                <i class='btn btn-danger btn-xs pull-right'
                   onclick='<?php echo $this->grid->get_f_edit(); ?>(<?php echo $record->getId(); ?>)'>
                    <?php echo $this->translate('Editar'); ?>
                </i>
            <?php endif; ?>

            <div class="clearfix"></div>
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <?php foreach ((array)$record as $key => $value): ?>
                        <tr>
                            <th><?php echo $this->translate($key); ?></th>

                            <td>
                                <?php if (substr($key, 0, 1) != '_'): ?>
                                    <?php if (is_object($value)): ?>
                                        <?php if (is_a($value, "DateTime")): ?>
                                            <?php echo $value->format("Y-m-d H:i:s"); ?>
                                        <?php elseif (is_a($value, 'Doctrine\ORM\PersistentCollection')): ?>
                                            <ul>
                                                <?php foreach ($value as $item) :?>
                                                    <li><?php echo $item; ?></li>
                                                <?php endforeach;?>
                                            </ul>
                                        <?php else: ?>
                                            <?php echo $value; ?>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php echo $value; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>

        </div>
    </div>

<?php echo $this->GridCrud($this->grid->getId()); ?>