<!-- Le styles -->
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('template/material-dashboard/css/material-dashboard.css'))
    ->prependStylesheet($this->basePath('template/material-dashboard/css/custom.css'))
    ->prependStylesheet($this->basePath('shared/font-awesome/css/font-awesome.min.css'))
    ->prependStylesheet($this->basePath('shared/bootstrap/css/bootstrap.min.css'))
    ->prependStylesheet($this->basePath('shared/material-icons/material-icons.css'))
;
?>
