<!-- Le styles -->
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('shared/material-dashboard/css/material-dashboard.css'))
    ->prependStylesheet($this->basePath('shared/font-awesome/css/font-awesome.min.css'))
    ->prependStylesheet($this->basePath('shared/adminlte/bootstrap/css/bootstrap.min.css'))
    //->appendStylesheet("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons", "text/css")
    //->appendStylesheet("https://fonts.googleapis.com/icon?family=Material+Icons");
    //->appendStylesheet($this->basePath('shared/material-dashboard/css/css')."?family=Roboto:300,400,500,700|Material+Icons", "text/css")
    //->appendStylesheet($this->basePath('shared/material-dashboard/css/icon')."?family=Material+Icons")
    ->prependStylesheet($this->basePath('shared/material-dashboard/material-icons/material-icons.css'))
;
?>
