<!-- Scripts -->
<?= $this->headScript()
//    ->prependFile($this->basePath('shared/material-dashboard/js/jquery.tagsinput.js'))
//    ->prependFile($this->basePath('shared/material-dashboard/js/nouislider.min.js'))
//    ->prependFile($this->basePath('shared/material-dashboard/js/arrive.min.js'))
//    ->prependFile($this->basePath('shared/material-dashboard/js/core.js'))
    ->prependFile($this->basePath('shared/material-dashboard/js/material-dashboard.js'))
    ->prependFile($this->basePath('shared/material-dashboard/js/perfect-scrollbar.jquery.min.js'))
    ->prependFile($this->basePath('shared/material-dashboard/js/material.min.js'))
    ->prependFile($this->basePath('shared/material-dashboard/js/bootstrap.min.js'))
    ->prependFile($this->basePath('shared/material-dashboard/js/jquery-3.2.1.min.js'))


;
?>


