<?php $this->layout()->setTemplate('layout/layout_login') ?>
<?php echo $this->flash(); ?>
<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">

        <div class="card card-login">
            <div class="card-header text-center" data-background-color="rose">
                <h4 class="card-title">Recovery</h4>
            </div>
            <div class="card-content">
                <?php echo $this->form()->openTag($form) ?>
                <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">email</i>
                                            </span>
                    <?php $element = $form->get('email'); ?>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <?php
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat('<span class="help-block">')
                            ->setMessageSeparatorString('</span><span class="help-block">')
                            ->setMessageCloseString('</span>')
                            ->render($element);
                        ?>

                    <?php endif; ?>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>


                <div class="footer text-center">
                    <?php echo $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-rose btn-simple btn-wd btn-lg')->setAttribute('value', $this->translate('Recovery'))); ?>
                </div>

                <?php echo $this->form()->closeTag($form); ?>
            </div>
            <div class="footer text-center">
                <a href="<?= $this->url('home'); ?>" class="text-center"><?= $this->translate('Ya tengo una membresía') ?></a>
            </div>
        </div>

    </div>
</div>