<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo $this->layoutHelper()->getTabTitle(); ?></title>

    <?php echo $this->partial('layout/partials/meta'); ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('template/adminlte/plugins/iCheck/square/blue.css'))
        ->prependStylesheet($this->basePath('template/adminlte/dist/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('template/adminlte/bootstrap/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('template/adminlte/ionicons/2.0.1/css/ionicons.min.css'))
        ->prependStylesheet($this->basePath('shared/font-awesome/css/font-awesome.min.css'));
    ?>


</head>
<body class="hold-transition login-page">

<!-- Main content -->
<section class="content">
    <?= $this->content ?>
</section>

<!-- Scripts -->
<?= $this->headScript()
    ->prependFile($this->basePath('template/adminlte/plugins/iCheck/icheck.min.js'))
    ->prependFile($this->basePath('template/adminlte/bootstrap/js/bootstrap.min.js'))
    ->prependFile($this->basePath('template/adminlte/plugins/jQuery/jquery-2.2.3.min.js'));
?>

<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>