<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><?php echo $this->layoutHelper()->getTabTitle();?></title>

	<?php echo $this->partial('layout/partials/meta'); ?>

	<?php echo $this->partial('layout/partials/css'); ?>

	<?php echo $this->partial('layout/partials/js'); ?>

	<style>
		h2,h3 {padding-left:14px;}
	</style>

</head>
<body class="hold-transition skin-blue sidebar-mini wysihtml5-supported skin-purple" id="body">
	<div class="wrapper">

		<header class="main-header">
			<!-- Logo -->
			<a href="<?= $this->url('home');?>" class="logo">
				<!-- mini logo for sidebar mini 50x50 pixels -->
				<span class="logo-mini"><b><?php echo $this->layoutHelper()->getTitle(); ?></b></span>
				<!-- logo for regular state and mobile devices -->
				<span class="logo-lg"><b><?php echo $this->layoutHelper()->getTitle(); ?></b></span>
			</a>
			<!-- Header Navbar: style can be found in header.less -->
			
			<nav class="navbar navbar-static-top">
				<!-- Sidebar toggle button-->
				<span class="sidebar-toggle" data-toggle="offcanvas" role="button">
					<span class="sr-only">Toggle navigation</span>
				</span>
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav navbar-right" style="margin-right: 1px">
						<?php echo $this->partial('zf-metal/security/menu/menu'); ?> 
					</ul>
				</div>
			</nav>
		</header>

		<?php echo $this->partial('layout/partials/menu_adminlte'); ?>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">

				<?php
				echo $this->navigation('default')->breadcrumbs()->setMinDepth(1)
				->setPartial('layout/breadcrumbs');
				?>

			</section>

			<!-- Main content -->
			<section class="content">
				<?= $this->content ?>
			</section>
		
		</div>
		<?php echo $this->partial('layout/footer'); ?>
</body>
</html>