<?php if ($user = $this->isAuthenticated()): ?>


    <li class="dropdown profile-dropdown">
        <a class="dropdown-toggle " data-toggle="dropdown" href="#">

            <!--Picture OR Icon-->
            <?php if($this->applicationOptions()->getShowImages()) : ?>
            <?php if ($user->getImg()): ?>
                <img src="<?php echo $this->getSecurityOptions()->getProfilePicturePathRelative() . $user->getImg(); ?>" >
            <?php else: ?>
                <i class="glyphicon glyphicon-user"></i>
            <?php endif; ?>
            <?php endif; ?>

            <!--Name, Username or Email-->    
            <span class="hidden-xs">
                <?php if ($user->getName()): ?>
                    <?php echo $user->getName(); ?>
                <?php elseif ($user->getUsername()): ?>
                    <?php echo $user->getUsername(); ?>
                <?php else: ?>
                    <?php echo $user->getEmail(); ?>
                <?php endif; ?>
            </span>

            <b class="fa  fa-caret-down" ></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/user/profile"><i class="fa fa-user"></i> <?php echo $this->translate('Perfil'); ?></a>
            </li>    


            <li class="divider"></li>
            <li><a href="/user/logout"><i class="fa fa-power-off"></i>  <?php echo $this->translate('Cerrar Sesión'); ?></a>
            </li>
        </ul>
    </li>

    <?php if ($this->isGranted("general-admin")): ?>
        <li class="dropdown profile-dropdown">
            <a class="dropdown-toggle " data-toggle="dropdown" href="#">
                <i class="glyphicon glyphicon-th-large"></i> 

                <b class="fa  fa-caret-down" ></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/admin/users"><i class="fa fa-user"></i> <?php echo $this->translate('Usuarios'); ?></a>
                </li>    
                <li class="divider"></li>
                <li><a href="/admin/roles"><i class="fa fa-cog"></i>  <?php echo $this->translate('Roles'); ?></a>
                </li>
                <li class="divider"></li>
                <li><a href="/admin/groups"><i class="fa fa-group"></i>  <?php echo $this->translate('Grupos'); ?></a>
                </li>

            </ul>
        </li>
    <?php endif; ?>

<?php else: ?>
    <li class="pull-right">
        <a href="/user/login"><i><?php echo $this->translate('Iniciar Sesión'); ?> </i> <i class="glyphicon glyphicon-log-in"> </i></a>
    </li>

<?php endif; ?>


