
<div class="pull-right">
    <a class="btn btnCustom" data-toggle="collapse" data-parent="#accordion" href="#collapseFilter_<?php echo $this->grid->getId(); ?>" aria-expanded="true" aria-controls="collapseFilter_<?php echo $this->grid->getId(); ?>" >
        <i class="fa fa-filter fa-lg"> </i> 
    </a>
</div>     
<div class="clearfix"></div>
<div class=" col-lg-12 col-xs-12">
    <div id="collapseFilter_<?php echo $this->grid->getId(); ?>" class="panel-body panel-collapse collapse"  role="tabpanel" aria-labelledby="headingOne">

        <?php
        $form = $this->grid->getFormFilters();
        ?>
        <?php
        echo $this->renderForm($form, "grid-filter", \ZfMetal\Commons\Consts::COLUMNS_THREE);
        ?>
    </div>
    <script type="text/javascript">
        function changeOp(element, value) {
            $('[name="' + element + '"]').val(value);
        }

        function resetFormFilter_<?php echo $form->getName(); ?>(sub = false) {
            $(':input', '#<?php echo $form->getName(); ?>')
                    .not(':button, :submit, :reset, :hidden')
                    .val('')
                    .removeAttr('checked')
                    .removeAttr('selected');

            if (sub === true) {
                $('#<?php echo $form->getName(); ?>').submit();
        }

        }

    </script>
</div>
