<?php $this->flashCurrent(); ?>
<div id="<?php echo $this->grid->getId(); ?>"  >
    
    <div class="box">
        <div class="box-header with-border">
            <div class="clearfix">

                <?php if ($this->grid->getOptions()->getTitle()): ?>
                    <h2 class="box-title pull-left"> <?php echo $this->grid->getOptions()->getTitle(); ?></h2>
                <?php endif; ?>



                <?php echo $this->partial($this->partialExports, array("grid" => $this->grid)); ?>

                <?php if ($this->grid->getOptions()->getCrudConfig()->getAdd()->getEnable()): ?>
                    <a <?php echo $this->grid->getCrudColumn()->getAdd()["action"]; ?>
                        class="btn pull-right btnCustom" style="margin-left:2px;"  >
                        <i class="fa fa-plus-circle fa-lg"></i> <?php echo $this->grid->getCrudColumn()->getAdd()["value"]; ?>
                    </a>
                <?php endif; ?>
                <?php if ($this->grid->getOptions()->getMultiSearchConfig()->getEnable()): ?>     
                    <?php echo $this->partial($this->partialSearch, array("grid" => $this->grid)); ?>
                <?php endif; ?>     


                <?php if ($this->grid->getOptions()->getMultiFilterConfig()->getEnable()): ?>
                    <?php echo $this->partial($this->partialFilter, array("grid" => $this->grid)); ?>
                <?php endif; ?>



            </div>
        </div>

        <div class="box-body">
           <div class="table-responsive">
            <table class="table table-bordered table-striped <?php echo $this->grid->getTableClass(); ?>">
                <!--HEADER-->
                <thead>
                    <tr>
                        <?php foreach ($this->grid->getColumns() as $column): ?>
                            <?php if (!$column->getHidden()): ?>
                                <th class="<?php echo $column->getThClass(); ?>">
                                    <?php echo $this->translate((string) $column); ?>
                                    <?php if ($column->getType() != "extra" && $column->getType() != "crud"): ?>
                                        
                                        <!--SORT-->
                                        <?php if ($this->grid->getSort() && $this->grid->getSort()->getBy() == $column->getName()): ?>
                                            <?php if ($this->grid->getSort()->getDirection() == "DESC"): ?>
                                                <a class="pull-right glyphicon glyphicon-sort-by-attributes-alt" href="<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "ASC") + $this->routeParams), true); ?>"></a>
                                            <?php elseif ($this->grid->getSort()->getDirection() == "ASC"): ?>
                                                <a class="pull-right glyphicon glyphicon-sort-by-attributes" href="<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>"></a>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <a class="pull-right glyphicon glyphicon-sort" href="<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => "DESC") + $this->routeParams), true); ?>"></a>
                                        <?php endif; ?>

                                    <?php endif; ?>

                                </th>
                            <?php endif; ?>
                        <?php endforeach; ?>

                    </tr>
                </thead>
                <tbody>
                    <!--BODY-->
                    <?php if (count($this->grid->getRow())): ?>
                        <?php foreach ($this->grid->getRow() as $data): ?>
                            <tr>
                                <?php foreach ($this->grid->getColumns() as $column): ?>
                                    <?php if (!$column->getHidden()): ?>
                                        <td class="<?php echo $column->getTdClass(); ?>">
                                            <?php //TODO - echo $column->getHtmlBegin(); ?>

                                            <?php echo $this->GridField($column, $data); ?>

                                            <?php //TODO - echo $column->getHtmlEnd(); ?>

                                        </td>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div> 

        <?php
        echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', $this->partialPagination, array("routeParams" => $this->routeParams,
            'route' => $this->route));
            ?>


            <?php echo $this->GridCrud($this->grid->getId()); ?>
            <!--MODAL-->
            <?php echo $this->partial($this->partialModal, array("grid" => $this->grid)); ?>
            
        </div>   
    </div>
</div>
