<?php
$this->notyFlash(true);
?>
<br><br>
<div class="row justify-content-md-center">
    <div class="col-md-4  col-xs-12">

        <div class="card">
            <div class="card-body">


                <?php echo $this->form()->openTag($form) ?>
                <h3 class="text-center cyan-text">
                    <i class="material-icons">vpn_key</i>
                    Login
                </h3>

                <div class="form-group">
                    <?php $element = $form->get('_username'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php echo $this->formElement($element); ?>
                    <?php if ($element->getOption('description')): ?>
                                   <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
                               <?php endif; ?>
                    <?php if ($this->formElementErrors($this->element)) : ?>
                        <?php
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat('<span class="help-block">')
                            ->setMessageSeparatorString('</span><span class="help-block">')
                            ->setMessageCloseString('</span>')
                            ->render($element);
                        ?>
                    <?php endif; ?>
                </div>

                <div class="form-group">
                    <?php $element = $form->get('_password'); ?>
                    <label> <?php echo $element->getOption('label'); ?> </label>
                    <?php
                    echo $this->formElement($element);
                    ?>
                    <?php if ($element->getOption('description')): ?>
                                   <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
                    <?php endif; ?>
                    <?php if ($this->formElementErrors($this->element)) : ?>
                        <?php
                        echo $this->formElementErrors()
                            ->setMessageOpenFormat('<span class="help-block">')
                            ->setMessageSeparatorString('</span><span class="help-block">')
                            ->setMessageCloseString('</span>')
                            ->render($element);
                        ?>
                         <?php endif; ?>
                </div>

                <?php if ($this->getSecurityOptions()->getRememberMe()) : ?>
                    <div class="">
                        <input type="hidden" name="_remember" />
                        <?php $element = $form->get('_remember');
                        ?>
                        <div class="switch">
                            <label>
                                <?php
                                echo $this->formElement($element);
                                ?>
                                <?php
                                echo $element->getLabel();
                                ?>
                            </label>
                        </div>
                    </div>
                <?php endif; ?>


                <div class="form-group">
                    <?php
                    $element = $form->get('submit')->setAttribute("class","btn btn-primary btn-block btn-raised");
                    echo $this->formElement($element);
                    ?>
                </div>


                <?php echo $this->form()->closeTag($form); ?>
            </div>

            <div class="container-fluid modal-footer">
                <div class="col-lg-12">
            <?php if ($this->getSecurityOptions()->getPublicRegister()): ?>

                <a class="float-left" href="<?php echo $this->basePath('/user/register'); ?>">
                        Register
                </a>

            <?php endif ?>

                <a class="float-right" href="<?php echo $this->basePath('/user/recovery'); ?>"> Password Recovery</a>
                </div>
            </div>
        </div>
    </div>
</div>
