<div id="<?php echo $this->grid->getId(); ?>" >
    <?php $this->flashCurrent(); ?>

    <div class="row">

        <div class="main-box-header clearfix addPaddingTopCustom">
            <?php if ($this->grid->getOptions()->getTitle()): ?>
                <h2 class="pull-left"> <?php echo $this->grid->getOptions()->getTitle(); ?></h2>
            <?php endif; ?>
            <div style="margin-right: 10px">
                <?php echo $this->partial($this->partialExports, array("grid" => $this->grid)); ?>

            </div>

            <div class="filter-block pull-right" style="margin-top: 0px; margin-right: 10px">


                <?php if ($this->grid->getOptions()->getMultiSearchConfig()->getEnable()): ?>     
                    <?php echo $this->partial($this->partialSearch, array("grid" => $this->grid)); ?>
                <?php endif; ?>     

                <?php if ($this->grid->getOptions()->getMultiFilterConfig()->getEnable()): ?>
                    <?php echo $this->partial($this->partialFilter, array("grid" => $this->grid)); ?>
                <?php endif; ?>

                <?php if ($this->grid->getOptions()->getCrudConfig()->getAdd()->getEnable()): ?>
                    <a <?php echo $this->grid->getCrudColumn()->getAdd()["action"]; ?>
                        class="btn pull-right btnCustom" >
                        <i class="fa fa-plus-circle fa-lg"></i> <?php echo $this->grid->getCrudColumn()->getAdd()["value"]; ?>
                    </a>
                <?php endif; ?>
            </div>
        </div>





        <div class="main-box-body clearfix">
            <div class="table-responsive">
                <table class="table table-hover dataTable no-footer <?php echo $this->grid->getTableClass(); ?>">
                    <thead>
                        <tr>
                            <?php foreach ($this->grid->getColumns() as $column): ?>
                                <?php if (!$column->getHidden()): ?>
                                    <th class="<?php echo $column->getThClass(); ?>">                                    
                                        <?php if ($column->getType() != "extra" && $column->getType() != "crud"): ?>
                                        <?php if ($this->grid->getSort() && $this->grid->getSort()->getBy() == $column->getName()): ?>
                                            <a class="linkCustom sorting_<?= strtolower($this->grid->getSort()->getDirection())?>" onclick="<?php echo \ZfMetal\Datagrid\C::F_SORT . $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => $this->grid->getSort()->getDirection()=='DESC'?'ASC':'DESC') + $this->routeParams), true); ?>')">
                                        <?php else: ?>
                                            <a class="linkCustom sorting" onclick="<?php echo \ZfMetal\Datagrid\C::F_SORT . $this->grid->getId(); ?>('<?php echo $this->url($this->route, array(), array('query' => array('sortBy' => $column->getName(), "sortDirection" => 'DESC') + $this->routeParams), true); ?>')">
                                        <?php endif; ?>
                                        <?php echo $this->translate((string) $column); ?> </a>
                                    <?php else: ?>
                                        <?php echo $this->translate((string) $column); ?>   
                                    <?php endif; ?>
                                    </th>
                                <?php endif; ?>
                            <?php endforeach; ?>

                        </tr>
                    </thead>
                    <tbody>
                        <?php if (count($this->grid->getRow())): ?>
                            <?php foreach ($this->grid->getRow() as $data): ?>
                                <tr>
                                    <?php foreach ($this->grid->getColumns() as $column): ?>
                                        <?php if (!$column->getHidden()): ?>
                                            <td class="<?php echo $column->getTdClass() ?>">
                                                <?php echo $column->getHtmlBegin(); ?>

                                                <?php echo $this->GridField($column, $data); ?>

                                                <?php echo $column->getHtmlEnd(); ?>

                                            </td>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <?php
        echo $this->paginationControl($this->grid->getPaginator(), 'Sliding', $this->partialPagination, array("routeParams" => $this->routeParams,
            'route' => $this->route, 'gridId' => $this->grid->getId()));
        ?>


        <?php echo $this->GridCrudAjaxModal($this->grid->getId(), $this->url($this->route, array(), array(), true)); ?>
    </div>
</div>