
<?php if ($this->pageCount): ?>

    <div class="row">
        <div class="col-sm-6">
            <div class="dataTables_info">
                <?php if ($this->applicationOptions()->getShowItemsRangePaginator()): ?>              
                    <span><?php echo $this->translate('Records'); ?>: <?php echo $this->totalItemCount; ?> | <?php echo $this->translate('Range'); ?>: <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?></span>
                <?php endif; ?>                 
            </div>
        </div>
        <div class="col-sm-6">
            <div class="dataTables_paginate paging_simple_numbers">
                <ul class="pagination pull-right" style="margin-right: 10px">

                    <!-- First page link -->
                    <li<?php echo (isset($this->previous)) ? '' : ' class="paginate_button disabled"'; ?>>
                        <a onclick="<?php echo \ZfMetal\Datagrid\C::F_PAGINATION.$this->gridId; ?>('<?php echo $this->url($this->route, array(), array('query' => array('page' => $this->first) + $this->routeParams), true); ?>')" ><i class="fa fa-angle-double-left"></i></a>

                    </li>

                    <!-- Previous page link -->
                    <li<?php echo (isset($this->previous)) ? '' : ' class="paginate_button disabled"'; ?>>
                        <a onclick="<?php echo \ZfMetal\Datagrid\C::F_PAGINATION.$this->gridId; ?>('<?php echo $this->url($this->route, array(), array('query' => array('page' => $this->previous) + $this->routeParams), true); ?>')" ><i class="fa fa-angle-left"></i></a>
                    </li>

                    <!-- Numbered page links -->
                    <?php foreach ($this->pagesInRange as $page): ?>
                        <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
                            <a onclick="<?php echo \ZfMetal\Datagrid\C::F_PAGINATION.$this->gridId; ?>('<?php echo $this->url($this->route, array(), array('query' => array('page' => $page) + $this->routeParams), true); ?>')" ><?php echo $page; ?></a>
                        </li>
                    <?php endforeach; ?>

                    <!-- Next page link -->
                    <li<?php echo (isset($this->next)) ? '' : ' class="paginate_button disabled"'; ?>>
                        <a onclick="<?php echo \ZfMetal\Datagrid\C::F_PAGINATION.$this->gridId; ?>('<?php echo $this->url($this->route, array(), array('query' => array('page' => $this->next) + $this->routeParams), true); ?>')" ><i class="fa fa-angle-right"></i></a>
                    </li>

                    <!-- Last page link -->
                    <li<?php echo (isset($this->next)) ? '' : ' class="paginate_button disabled"'; ?>>
                        <a onclick="<?php echo \ZfMetal\Datagrid\C::F_PAGINATION.$this->gridId; ?>('<?php echo $this->url($this->route, array(), array('query' => array('page' => $this->last) + $this->routeParams), true); ?>')" ><i class="fa fa-angle-double-right"></i></a>

                    </li>

                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
