<li class="<?php if ($page->isActive(true)) echo ' active' ?>">
    <a data-toggle="collapse" href="#<?php echo str_replace(" ", "", $this->page->getLabel()); ?>" aria-expanded="false"
        <?php if ($this->page->getTarget() != ""): ?>
            target="<?php echo $this->page->getTarget(); ?>"
        <?php endif; ?>
    >
        <?php if ($this->page->get("icon") !== ""): ?>
            <i class="material-icons"><?php echo $this->page->get("icon"); ?></i>
        <?php else : ?>
            <i class="material-icons">timeline</i>
        <?php endif; ?>

        <p> <?php echo $this->page->getLabel() ?>
            <b class="caret"></b>
        </p>

    </a>
    <div class="collapse" aria-expanded="false" id="<?php echo str_replace(" ", "", $this->page->getLabel()); ?>">
        <ul class="nav">
            <?php foreach ($page->getPages() as $child): ?>
                <?php if (!$this->navigation()->accept($child)) continue; ?>
                <?php if ($child->get("separator") === true): ?>
                    <li role="separator" class="divider"></li>
                    <?php
                    continue;
                endif;
                ?>

                <?php if (!$child->hasPages()): ?>
                    <?php echo $this->partial("zf-metal/commons/menu/vertical/partial/child", array("page" => $child)); ?>
                <?php else: ?>
                    <?php
                    //check if access is allowed at least one item
                    $access = false;
                    foreach ($child->getPages() as $subChild) {
                        if ($this->navigation()->accept($subChild) && $subChild->get("separator") !== true) {
                            $access = true;
                        }
                    }
                    ?>
                    <?php if ($access) : ?>
                        <?php echo $this->partial("zf-metal/commons/menu/vertical/partial/dropdown", array("page" => $child)); ?>
                    <?php endif; ?>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    </div>
</li>  
