<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo $this->layoutHelper()->getTabTitle();?></title>


    <?php echo $this->partial('layout/partials/meta'); ?>

    <?php echo $this->partial('layout/partials/css'); ?>

    <?php echo $this->partial('layout/partials/js'); ?>


</head>
<body class="off-canvas-sidebar">

<!-- Main content -->
<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" filter-color="black" data-image="shared/material-dashboard/img/login.jpeg">
        <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
        <div class="content">
            <div class="container">
                <?= $this->content ?>
            </div>
        </div>
    </div>
</div>

</body>
</html>