<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>TITLE</title>

    <?php echo $this->partial('layout/partials/meta'); ?>

    <?php echo $this->partial('layout/partials/css'); ?>

    <?php echo $this->partial('layout/partials/js'); ?>

    <style>
        h2, h3 {
            padding-left: 14px;
        }
    </style>

</head>
<body>
<div class="wrapper">

    <?php echo $this->partial('layout/sidebar'); ?>


    <div class="main-panel ps-container ps-theme-default ps-active-y">

        <?php echo $this->partial('layout/navtop'); ?>

        <!-- Main content -->
        <div class="content">
            <?= $this->content ?>
        </div>
        <?php echo $this->partial('layout/footer'); ?>
    </div>


</body>
</html>