<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                <i class="material-icons visible-on-sidebar-mini">view_list</i>
            </button>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"> Title Example (navtop.phtml) </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php if ($this->isGranted("general-admin")): ?>
                <li>
                    <a href="/admin/panel" rel="tooltip" data-original-title="Panel de Administrador" data-placement="bottom">
                        <i class="material-icons">dashboard</i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                </li>
                <?php endif; ?>

                <?php if ($user = $this->isAuthenticated()): ?>
                <li>
                    <a href="/user/logout" rel="tooltip" data-original-title="Salir" data-placement="bottom" >
                        <i class="material-icons">exit_to_app</i>
                        <p class="hidden-lg hidden-md">Salir</p>
                    </a>
                </li>
                <?php else: ?>
                    <li>
                        <a href="/user/login" rel="tooltip" data-original-title="Iniciar Sesión" data-placement="bottom" >
                            <i class="material-icons">vpn_key</i>
                            <p class="hidden-lg hidden-md">Iniciar Sesión</p>
                        </a>
                    </li>
                <?php endif; ?>
                <li class="separator hidden-lg hidden-md"></li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group form-search is-empty">
                    <input type="text" class="form-control" placeholder=" Search ">
                    <span class="material-input"></span>
                    <span class="material-input"></span></div>
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                    <i class="material-icons">search</i>
                    <div class="ripple-container"></div>
                </button>
            </form>
        </div>
    </div>
</nav>