<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <!--        <div class="navbar-minimize">
                    <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                        <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                        <i class="material-icons visible-on-sidebar-mini">view_list</i>
                    </button>
                </div>-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"> <?php echo $this->layoutHelper()->getPageTitle(); ?> </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <?php if ($user = $this->isAuthenticated()): ?>
                    <li>
                        <a href="/user/logout" rel="tooltip" data-original-title="Salir" data-placement="bottom">
                            <i class="material-icons">exit_to_app</i>
                            <p class="hidden-lg hidden-md">Salir</p>
                        </a>
                    </li>

                    <?php if ($this->isGranted("general-admin")): ?>
                        <li class="dropdown profile-dropdown">
                            <a class="dropdown-toggle " data-toggle="dropdown" href="#">
                                <i class="fa fa-ellipsis-v"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="/admin/users"><i
                                                class="fa fa-user"></i> <?php echo $this->translate('Usuarios'); ?></a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="/admin/roles"><i
                                                class="fa fa-cog"></i> <?php echo $this->translate('Roles'); ?></a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="/admin/groups"><i
                                                class="fa fa-group"></i> <?php echo $this->translate('Grupos'); ?></a>
                                </li>

                            </ul>
                        </li>
                    <?php endif; ?>
                <?php else: ?>
                    <li>
                        <a href="/user/login" rel="tooltip" data-original-title="Iniciar Sesión"
                           data-placement="bottom">
                            <i class="material-icons">vpn_key</i>
                            <p class="hidden-lg hidden-md">Iniciar Sesión</p>
                        </a>
                    </li>
                <?php endif; ?>
                <li class="separator hidden-lg hidden-md"></li>
            </ul>

        </div>
    </div>
</nav>