<div class="sidebar" data-active-color="rose" data-background-color="white"
     data-image="<?= $this->basePath(); ?>/shared/material-dashboard/img/sidebar-1.jpg">
    <!-- Logo -->
    <div class="logo text-center">
        <?php echo $this->layoutHelper()->getTitle();?>
    </div>


    <div class="sidebar-wrapper ps-container ps-theme-default ps-active-y">
        <?php if ($user = $this->isAuthenticated()): ?>
            <div class="user">
                <div class="photo">

                    <?php if ($user && $user->getImg()): ?>
                        <img src="<?php echo $this->getSecurityOptions()->getProfilePicturePathRelative() . $user->getImg(); ?>">
                    <?php else : ?>
                        <img src="/img/axion-logo-mini.png">
                    <?php endif; ?>

                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                        <span>
                                 <?php if ($user && $user->getName()) {
                                     echo $user->getName();
                                 } elseif ($user && $user->getUsername()) {
                                     echo $user->getUsername();
                                 } ?>
                            </span>

                    </a>

                </div>
            </div>
        <?php endif; ?>

        <?php
        echo $this->renderMenu(\ZfMetal\Commons\Consts::STYLE_MENU_VERTICAL, "", "nav");
        ?>

    </div>

</div>