<a class="btn btn-default btn-raised" href="/admin/groups"><?php echo $this->translate('Admin Groups'); ?></a>
<div class="clearfix"></div>

<div class="row justify-content-md-center">
    <div class="col-md-10  col-xs-12">

        <div class="card">
            <div class="card-body">
                <table class="table table-striped table-right">
                    <tr>
                        <th class="text-right">Id:</th>
                        <td class="text-left"><?php echo $this->group->getId(); ?></td>
                    </tr>

                    <tr>
                        <th class="text-right">Nombre:</th>
                        <td class="text-left"><?php echo $this->group->getName(); ?></td>
                    </tr>


                    <tr>
                        <th class="text-right"><?php echo $this->translate('Usuarios'); ?></th>
                        <td class="text-left">
                            <ul>
                                <?php foreach ($this->group->getUsers() as $r): ?>
                                    <li><?php echo $r->getName(); ?></li>

                                <?php endforeach; ?>
                            </ul>
                        </td>
                    </tr>


                </table>
            </div>
            <div class="col-lg-4">

            </div>

        </div>
    </div>
</div>


