<?php $this->layout()->setTemplate('layout/loginLayout') ?>

<div class="row">
    <div id="login-box">
        <div class="row">
            <div class="col-xs-12">
                <header id="login-header">
                    <div id="login-logo">
                        <?php if ($this->applicationOptions()->getShowImages()) : ?>
                        <img src="<?= $this->basePath('shared/centaurus');?>/img/logo.png" alt="">
                        <?php endif; ?>
                    </div>
                </header>
                <div id="login-box-inner">

                    <?php echo $this->form()->openTag($form) ?>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <?php $element = $form->get('name')->setAttribute('placeholder', $this->translate('Nombre Completo')); ?>
                        <?php echo $this->formElement($element); ?>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        <?php $element = $form->get('email')->setAttribute('placeholder', $this->translate('Email')); ?>
                        <?php echo $this->formElement($element); ?>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-user"></i></span>
                        <?php $element = $form->get('username')->setAttribute('placeholder', $this->translate('Usuario')); ?>
                        <?php echo $this->formElement($element); ?>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <?php $element = $form->get('password')->setAttribute('placeholder', $this->translate('Clave')); ?>
                        <?php echo $this->formElement($element); ?>
                    </div>

                    <!--                    <div id="remember-me-wrapper">
                                            <div class="row">
                                                <div class="col-xs-12">
                                                    <div class="checkbox-nice">
                                                        <input id="terms-cond" checked="checked" type="checkbox">
                                                        <label for="terms-cond">
                                                            I accept terms and conditions
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>-->
                    <div class="row">
                        <div class="col-xs-12">
                            <?php echo $this->formElement($form->get('submit')->setAttribute('value', $this->translate('Registrar'))); ?>
                        </div>
                        <div class="col-xs-12">
                            <br>
                            <a href="<?= $this->url('zf-metal.user/login')?>" id="login-forget-link" class="forgot-link col-xs-12"><?= $this->translate('Volver a Login') ?></a>
                        </div>
                    </div>
                    
                    <?php echo $this->form()->closeTag($form); ?>
                </div>
            </div>
        </div>
    </div>
</div>
