<div class="block block-drop-shadow">
    <div class="head bg-dot20">
        <h2>Usuarios</h2>
        <div class="side pull-right">
            <ul class="buttons">
                <li><a href="#"><span class="icon-cogs"></span></a></li>
            </ul>
        </div>
        <div class="head-subtitle">Creando Usuario</div>



        <?php
        $groups = [
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'User',
                'title' => "",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['name', 'username', 'email', 'password']
            ],
            [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'enableUser',
                'title' => null,
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['active', 'roles']
            ],
        ];


        $this->form->remove('groups');

        $this->form->get('submit')->setAttribute('value', 'Enviar')
            ->setAttribute('class', 'pull-right btn btn-primary')
            ->setAttribute('style', 'margin-left: 2px');

        $this->form->add(array(
            'name' => 'cancel',
            'type' => 'Zend\Form\Element\Button',
            'attributes' => array(
                'value' => "Cancelar",
                'class' => 'pull-right btn btn-default',
                'onclick' => 'window.location.href="' . $this->url('zf-metal.admin/users', array(), array('query' => $this->routeParams), true) . '"',
            ),
            'options' => array(
                'label' => 'Cancelar',
            )
        ));

        $this->form->get('name')
            ->setAttribute('placeholder', 'Nombre')
            ->setLabel('Nombre');
        $this->form->get('username')
            ->setAttribute('placeholder', 'Usuario')
            ->setLabel('Usuario');
        $this->form->get('email')
            ->setAttribute('value', '');
        ?>
        <div class="head-panel">
            <?php
            echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_TWO, $groups);
            ?>
        </div>
    </div>
</div>


