<?php $this->layout()->setTemplate('layout/loginLayout') ?>
<?php echo $this->flashCurrent(); ?>

<div class="row">
    <div class="col-xs-12">
        <div id="login-box">
            <div id="login-box-holder">
                <div class="row">
                    <div class="col-xs-12">
                        <header id="login-header">

                            <div id="login-logo">

                                <?php echo $this->layoutHelper()->getTitle();?>

                            </div>

                        </header>
                        <div id="login-box-inner">
                            <?php
                            $form = $this->form;
                            $form->prepare();
                            ?>

                            <?php echo $this->form()->openTag($form) ?>
                            <?php $element = $form->get('_username')->setAttribute('placeholder', 'Usuario o Email') ?>
                            <div class="input-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                <?php $element->setAttribute('class', "form-control"); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php if ($this->formElementErrors($element)) :
                                    ?>
                                    <?php
                                    echo $this->formElementErrors()
                                            ->setMessageOpenFormat('<p class="help-block">')
                                            ->setMessageSeparatorString('</p><p class="help-block">')
                                            ->setMessageCloseString('</p>')
                                            ->render($element);
                                    ?>
                                <?php endif; ?>
                            </div>
                            <?php $element = $form->get('_password')->setAttribute('placeholder', 'Clave') ?>
                            <div class="input-group  <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                                <span class="input-group-addon"><i class="fa fa-key"></i></span>
                                <?php $element->setAttribute('class', "form-control"); ?>
                                <?php echo $this->formElement($element); ?>


                                <?php if ($this->formElementErrors($element)) :
                                    ?>
                                    <?php
                                    echo $this->formElementErrors()
                                            ->setMessageOpenFormat('<p class="help-block">')
                                            ->setMessageSeparatorString('</p><p class="help-block">')
                                            ->setMessageCloseString('</p>')
                                            ->render($element);
                                    ?>
                                <?php endif; ?>
                            </div>


                            <div id="remember-me-wrapper">
                                <div class="row">
                                    <?php if ($this->getSecurityOptions()->getRememberMe()) : ?>
                                        <?php
                                        $element = $form->get('_remember')->setAttribute('type', 'checkbox')
                                                ->setAttribute('id', 'remember-me')
                                                ->setAttribute('class', '');
                                        ?>
                                        <div class="col-xs-6">
                                            <div class="checkbox-nice">
                                                <?php echo $this->formElement($element->setLabel('Recuérdame')); ?>
                                                <label for="remember-me">
                                                    <?php echo ucfirst($this->translate($element->setAttribute('for', 'remember-me')->getLabel())); ?>
                                                </label>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($this->getSecurityOptions()->getPasswordRecovery()) : ?>
                                        <a href="<?= $this->url('zf-metal.user/recovery') ?>" id="login-forget-link" class="col-xs-6">
                                            <?= $this->translate('Recuperar Password'); ?>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <?php $element = $form->get('submit')->setValue('Iniciar Sesión')->setAttribute('class', 'btn btn-success col-xs-12'); ?>
                            <div class="row">
                                <div class="col-xs-12">
                                    <?php echo $this->formElement($element); ?>
                                </div>
                            </div>

                            <?php echo $this->form()->closeTag(); ?>

                        </div>
                    </div>
                </div>
            </div>

        </div>

        <?php if ($this->getSecurityOptions()->getPublicRegister()) : ?>
            <div id="login-box-footer">
                <div class="row">
                    <div class="col-xs-12">
                        <?= $this->translate('Tienes una cuenta?') ?>
                        <a href="<?php echo $this->url('zf-metal.user/register'); ?>">
                            <?= $this->translate('Regístrate') ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class='text-center'>
        </div>
    </div>
</div>
