<div class="row">
    <div class="page-footer">
        <div class="page-footer-wrap">
            <div class="side pull-left">
                Copyirght &COPY;  <?php echo $this->layoutHelper()->getCopyright(); ?>
                <script>
                document.write(new Date().getFullYear())
                </script>. All rights reserved. Created by <?php echo $this->layoutHelper()->getAuthor(); ?>
            </div>
        </div>
    </div>
</div>

