<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo $this->layoutHelper()->getTabTitle(); ?></title>

    <?php echo $this->partial('layout/partials/meta'); ?>

    <?php echo $this->partial('layout/partials/css'); ?>

    <?php echo $this->partial('layout/partials/js'); ?>

    <style>
        h2, h3 {
            padding-left: 14px;
        }
    </style>

</head>
<body class="bg-img-num1">
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <?php echo $this->partial('layout/navtop'); ?>
        </div>
    </div>

    <div class="">
        <?= $this->content ?>
    </div>

    <div class="row">
    <?php echo $this->partial('layout/footer'); ?>
    </div>
</div>



</body>
</html>