<?php $this->layout()->setTemplate('layout/layout_login_adminlte') ?>
<?php
$this->notyFlash(true);
?>
<div class="register-box">
  <div class="register-logo">
    <a href="<?= $this->url('home'); ?>"><b>BigBrother</b> 2</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg"><?= $this->translate('Register a new membership'); ?></p>

    <?php echo $this->form()->openTag($form) ?>
      <div class="form-group has-feedback">
      <?php $element = $form->get('name')->setAttribute('class','form-control'); ?>
                <?php echo $this->formElement($element); ?>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
      <?php $element = $form->get('email')->setAttribute('class','form-control'); ?>
                <?php echo $this->formElement($element); ?>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
      <?php $element = $form->get('username')->setAttribute('class','form-control'); ?>
                <?php echo $this->formElement($element); ?>
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
      <?php $element = $form->get('password')->setAttribute('class','form-control'); ?>
                <?php echo $this->formElement($element); ?>
         <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">

         <?php echo $this->formElement($form->get('submit')->setAttribute('class','btn btn-primary btn-block btn-flat')->setAttribute('value', $this->translate('Register'))); ?>
      
      </div>
<?php echo $this->form()->closeTag($form); ?>

    <a href="<?= $this->url('home'); ?>" class="text-center"><?= $this->translate('I already have a membership'); ?></a>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->
