<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/shared/font-awesome/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath() . '/template/centaurus/bootstrap/css/bootstrap.min.css')
        ->appendStylesheet($this->basePath() . '/template/centaurus/global/theme_styles.css')
        ->appendStylesheet($this->basePath() . '/template/centaurus/global/custom.css')

;
?> 

<link href="//fonts.googleapis.com/css?family=Open+Sans:400,600,700,300|Titillium+Web:200,300,400" rel="stylesheet" type="text/css">