<?php
echo $this->headScript()
        ->prependFile($this->basePath() . '/template/centaurus/global/CookieManager.js')
        ->prependFile($this->basePath() . '/template/centaurus/theme/scripts.js')
        ->prependFile($this->basePath() . '/template/centaurus/global/jquery.nanoscroller.min.js')
        ->prependFile($this->basePath() . '/template/centaurus/global/bootstrap.js')
        ->prependFile($this->basePath() . '/template/centaurus/global/jquery-2.2.4.min.js')
        ->appendScript($this->partial('layout/js/nav.js'), 'text/javascript');
?>


