<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>Centaurus - Bootstrap Admin Template</title>

        <?= $this->partial('layout/css')?>
    </head>
    <body id="login-page">
        <div class="container">
            <?= $this->content; ?>
        </div>

    </body>
</html>