<div class="card">
    <div class="card-header card-header-icon" data-background-color="rose">
        <i class="material-icons">assignment</i>
    </div>
    <div class="card-content">
        <h4 class="card-title">Detalle de Usuario</h4>
        <div class="clearfix"></div>

        <a class="btn btn-default btn-xs pull-right"
           href="/admin/users">
            <?php echo $this->translate('Listar'); ?>
        </a>

        <a href="/admin/users/edit/<?php echo $this->user->getId(); ?>" class="btn btn-danger btn-xs pull-right"><?php echo $this->translate('Editar'); ?></a>

        <div class="clearfix"></div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <tr>
                    <th class="text-right">Id:</th>
                    <td class="text-left"><?php echo $this->user->getId(); ?></td>
                </tr>

                <tr>
                    <th class="text-right">Nombre:</th>
                    <td class="text-left"><?php echo $this->user->getName(); ?></td>
                </tr>

                <tr>
                    <th class="text-right">Usuario:</th>
                    <td class="text-left"><?php echo $this->user->getUsername(); ?></td>
                </tr>

                <tr>
                    <th class="text-right">Email:</th>
                    <td class="text-left"><?php echo $this->user->getEmail(); ?></td>
                </tr>

                <tr>
                    <th class="text-right">Active:</th>
                    <td class="text-left"><?php echo $this->user->getActive(); ?></td>
                </tr>

                <tr>
                    <th class="text-right">Roles:</th>
                    <td class="text-left">
                        <ul>
                            <?php foreach ($this->user->getRoles() as $role): ?>
                                <li><?php echo $role->getName(); ?></li>

                            <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>

                <tr>
                    <th class="text-right">Groups:</th>
                    <td class="text-left">
                        <ul>
                            <?php foreach ($this->user->getGroups() as $group): ?>
                                <li><?php echo $group->getName(); ?></li>

                            <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>
            </table>
        </div>

    </div>
</div>


