<div class="login-block">
    <div class="block block-transparent"> 
        <h3><?php echo $this->translate('Recuperar Password'); ?></h3>
        <?php
        $form = $this->form;
        $form->prepare();
        $element = $form->get("email");
        $element->setLabel(null);
        ?>
        <?php echo $this->form()->openTag($form); ?>


        <div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
            <div class="input-group">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                </div>
                <?php echo $this->formInput($element); ?>
            </div>


            <?php if ($this->formElementErrors($element)) : ?>
                <?php
                // Imprimo los errores
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<span class="help-block">')
                        ->setMessageSeparatorString('</span><span class="help-block">')
                        ->setMessageCloseString('</span>')
                        ->render($element);
                ?>
            <?php endif; ?>
        </div>
        
        <div class="clearfix"></div>
        <?php $element = $form->get("submit"); ?>
        <?php echo $this->formElement($element); ?>
        <?php echo $this->form()->closeTag($form); ?>

    </div>
</div>