<?php

return [
    //ZF
    'Zend\Mvc\Plugin\Identity',
    'Zend\I18n',
    'Zend\Mail',
    'Zend\Cache',
    'Zend\Paginator',
    'Zend\Form',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Mvc\Plugin\FlashMessenger',
    'Zend\Session',
    'Zend\Hydrator',
    'Zend\Router',
    'Zend\Validator',
    'Zend\Navigation',
    //DOCTRINE
    'DoctrineModule',
    'DoctrineORMModule',
    'SwissEngine\Tools\Doctrine\Extension',
    //ZFMETAL
    'ZfMetal\Log',
    'ZfMetal\Mail',
    'ZfcRbac',
    'ZfMetal\Security',
    'ZfMetal\SecuritySocial',
    'ZfMetal\Commons',
    'ZfMetal\Datagrid',
    'ZfMetal\Generator',
    //MODULES
    'Application',
    'Prueba',
];
