<?php $this->layoutHelper()->setPageTitle("Perfil - Modificación de contraseña");?>
<div class="row ">
    <div class="container-fluid">
        <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">
            <div class="card">
                <div class="card-header card-header-icon" data-background-color="rose">
                    <i class="material-icons">lock</i>
                </div>
                <div class="clearfix"></div>
                <div class="card-content">
                    <h4 class="card-title">Modificar contraseña</h4>


                    <?php echo $this->form()->openTag($formManual) ?>

                    <?php
                    $element = $formManual->get('password')
                        ->setAttribute('placeholder', 'Contraseña')
                        ->setLabel('Contraseña');
                    $element->setOption("addon", "fa fa-lock");
                    ?>
                    <?php echo $this->renderFormElement($element, "vertical"); ?>


                    <?php
                    $element = $formManual->get('password_verify')
                        ->setAttribute('placeholder', 'Verificar Contraseña')
                        ->setLabel('Verificar Contraseña');
                    $element->setOption("addon", "fa fa-lock");
                    ?>
                    <?php echo $this->renderFormElement($element, "vertical"); ?>

                    <div class="clearfix"></div>

                    <?php
                    $element = $formManual->get('submit');
                    $element->setAttribute('class', 'btn btn-primary btnCustom pull-right');
                    $element->setValue('Enviar');
                    ?>

                    <?php echo $this->renderFormElement($element, "vertical"); ?>
                    <a class="pull-right btn btnCancelCustom" style="margin-right: 2px;"
                       href="/user/profile"><?php echo $this->translate('Volver'); ?></a>

                    <?php echo $this->form()->closeTag($formManual); ?>
                </div>
            </div>
        </div>
    </div>
</div>