<?php if ($user = $this->isAuthenticated()): ?>


    <ul class="navbar-nav">
        <li class="nav-item">
        <?php if ($user->getImg()): ?>
            <div class="avatar float-left">
                <img src="<?php echo $this->getSecurityOptions()->getProfilePicturePathRelative() . $user->getImg(); ?>"
                     class="media-object" alt="">
            </div>
        <?php endif; ?>

        <button class="btn dropdown-toggle" type="button" id="muser" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            <?php if ($user->getName()): ?>
                <?php echo $user->getName(); ?>
            <?php elseif ($user->getUsername()): ?>
                <?php echo $user->getUsername(); ?>
            <?php else: ?>
                <?php echo $user->getEmail(); ?>
            <?php endif; ?>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="muser">
            <a class="dropdown-item" href="/user/profile"><?php echo $this->translate('Perfil'); ?></a>
            <a class="dropdown-item" href="/user/logout"> <?php echo $this->translate('Cerrar Sesión'); ?></a>
        </div>
        </li>

        <?php if ($this->isGranted("general-admin")): ?>
        <li class="nav-item">
            <button class="btn bmd-btn-icon  bmd-btn-fab-sm dropdown-toggle" type="button" id="ex1"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">more_vert</i>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="ex1">
                <a href="/admin/users">
                    <button class="dropdown-item"
                            type="button"> <?php echo $this->translate('Usuarios'); ?></button>
                </a>
                <div class="dropdown-divider"></div>
                <a href="/admin/roles">
                    <button class="dropdown-item" type="button">  <?php echo $this->translate('Roles'); ?></button>
                </a>
                <div class="dropdown-divider"></div>
                <a href="/admin/groups">
                    <button class="dropdown-item" type="button">  <?php echo $this->translate('Grupos'); ?></button>
                </a>

            </div>
        </li>
        <?php endif; ?>

    </ul>


<?php else: ?>
<ul class="navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="/user/login">
            <i><?php echo $this->translate('Iniciar Sesión'); ?> </i>
        </a>
    </li>
    <ul>
        <?php endif; ?>


