<?php
//REMOVE CLASS "form-control" if  setted
$class = $this->element->getAttribute("class");
if (preg_match("/form-control/", $class)) {
    $this->element->setAttribute("class",str_replace("form-control","", $class));
}

$this->element->setLabelAttributes(['class' => 'col']);
?>

<div  class="checkbox <?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">

    <?php echo $this->formElement($this->element); ?>
    <?php echo ucfirst($this->translate($this->element->getLabel())); ?>



    <?php if ($element->getOption('description')): ?>
        <p class="bmd-help"><?php echo $this->element->getOption('description') ?></p>
    <?php endif; ?>

    <?php if ($this->formElementErrors($this->element)) : ?>
        <?php
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<span class="bmd-help">')
                ->setMessageSeparatorString('</span><span class="bmd-help">')
                ->setMessageCloseString('</span>')
                ->render($this->element);
        ?>

    <?php endif; ?>

</div>
