<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/shared/centaurus/libraries/select2/select2.css');
$this->headScript()->appendFile($this->basePath() . '/shared/centaurus/libraries/select2/select2.min.js');

?>
<div class="row ">
    <div class="main-box  clearfix">

        <div class="main-box-header clearfix addPaddingTopCustom">
            <h2 style="padding: 7px;"> Edición de Usuario</h2>
        </div>


        <div class="main-box-body clearfix">
            <?php
            $groups = [
                    [
                    'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                    'id' => 'User',
                    'title' => "",
                    'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                    'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                    'fields' => ['name', 'username', 'email', 'password']
                ],
                    [
                    'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                    'id' => 'enableUser',
                    'title' => null,
                    'columns' => \ZfMetal\Commons\Consts::COLUMNS_TWO,
                    'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                    'fields' => ['active','roles']
                ],

            ];


            $this->form->add([
                'type' => 'DoctrineModule\Form\Element\ObjectSelect',
                'name' => 'roles',
                'attributes' => array(
                    'multiple' => 'multiple',
                    'id' => 'multiSelectRoles',
                    'class' => '',
                ),
                'options' => [
                    'object_manager' => $this->form->getEm(),
                    'target_class' => 'ZfMetal\Security\Entity\Role',
                    'property' => 'name',
                    'label' => 'Roles',
                    'find_method' => [
                    'name' => 'getAssignableRoles',
                    'params' => [
                        'name' => 'invitado',
                    ],
                    ],
                ],
            ]);

            $this->form->remove('active');

            $this->form->add(array(
                'type' => 'Zend\Form\Element\Select',
                'name' => 'active',
                'options' => array(
                    'label' => 'Estado',
                    'value_options' => array(
                        '1' => 'Activo',
                        '0' => 'Inactivo',
                    ),
                ),
                'attributes' => array(
                    'placeholder' => 'Estado',
                ),
            )
            );

            $this->form->remove('groups');

            $this->form->get('submit')->setAttribute('value', 'Enviar')
                    ->setAttribute('class', 'pull-right btn btnCustom')
                    ->setAttribute('style', 'margin-left: 2px');

            $this->form->add(array(
                'name' => 'cancel',
                'type' => 'Zend\Form\Element\Button',
                'attributes' => array(
                    'value' => "Cancelar",
                    'class' => 'pull-right btn btnCancelCustom',
                    'onclick' => 'window.location.href="' . $this->url('zf-metal.admin/users', array(), array('query' => $this->routeParams), true) . '"',
                ),
                'options' => array(
                    'label' => 'Cancelar',
                )
            ));
            
            $this->form->bind($this->form->getObject());

            $this->form->get('name')
                    ->setAttribute('placeholder', 'Nombre')
                    ->setLabel('Nombre');
            $this->form->get('username')
                    ->setAttribute('placeholder', 'Usuario')
                    ->setLabel('Usuario');

            echo $this->renderForm($this->form, 'vertical-select2', \ZfMetal\Commons\Consts::COLUMNS_TWO, $groups);
            ?>
        </div>

    </div>
</div>

<style>
    .multi-check label{
        padding: 10px ! important;
        margin: 5px ! important;
    }

</style>

<script type="text/javascript">
    $('#multiSelectRoles').select2({
        placeholder: 'Selecciones los roles',
        allowClear: true
    });
</script>