
<div class="row ">
    <div class="main-box  clearfix">

        <div class="main-box-header clearfix">
            <h2> Gestionando Passoword de Usuario</h2>
        </div>


        <div class="main-box-body clearfix">



            <div class="col-md-6 col-md-offset-3">
                <h4 class="text-center">Usuario: <?php echo $this->user->getUsername(); ?></h4>
                <?php echo $this->form()->openTag($formAuto) ?>
                <legend>Auto Reset</legend>

                <div class="row">
                    <div class="col-xs-12 col-md-12 radio">
                        <?php echo $this->formElement($formAuto->get('submit')); ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag($formAuto); ?>
                <br><br>
                <?php echo $this->form()->openTag($formManual) ?>
                <legend>Manual Reset</legend>
                <!--<h4>Por favor completa el siguiente formulario.</h4>-->
                <div class="row">
                    <div class="col-xs-12 col-md-6">
                        <div class="form-group">
                            <?php $element = $formManual->get('password'); ?>
                            <label> <?php echo $element->getOption('label'); ?> </label>
                            <?php echo $this->formElement($element); ?>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <div class="form-group">
                            <?php $element = $formManual->get('password_verify'); ?>
                            <label> <?php echo $element->getOption('label'); ?> </label>
                            <?php echo $this->formElement($element); ?>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12 col-md-12 radio">
                        <?php echo $this->formElement($formManual->get('submit')); ?>
                    </div>
                </div>

                <?php if ($formManual->getMessages()): ?>
                    <?php foreach ($formManual->getMessages() as $msjs): ?>
                        <?php foreach ($msjs as $key => $msj): ?>
                            <div class="alert alert-danger"><?php echo $msj; ?></div>

                        <?php endforeach; ?>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php echo $this->form()->closeTag($formManual); ?>

            </div>
            <div class="clearfix"></div>
            <div class="filter-block pull-right" style="margin-top: 25px; margin-right: 10px">
                <a class="btn btnCustom" href="/admin/users">Listar usuarios</a>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

