<li class=" nav-item dropdown pull-xs-right <?php if ($page->isActive(true)) echo ' active' ?>">
    <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <?php if ($page->get("icon") !== ""): ?>
            <span class="<?php echo $page->get("icon"); ?>"></span>
        <?php endif; ?>
        <?php echo $page->getLabel() ?>
    </a>
    <ul class="dropdown-menu dropdown-menu-left">
        <?php foreach ($page->getPages() as $child): ?>
            <?php if (!$this->navigation()->accept($child)) continue; ?>
            <?php if ($child->get("separator") === true): ?>
                <li role="separator" class="divider"></li>
                    <?php
                    continue;
                endif;
                ?>
            <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                <a  class="dropdown-item"
                    href="<?php echo $child->getHref() ?>"
                    <?php if ($child->getTarget() != ""): ?>
                        target="<?php echo $child->getTarget(); ?>"
                    <?php endif; ?> >
                        <?php if ($child->get("icon") !== ""): ?>
                        <span class="<?php echo $child->get("icon"); ?>"></span>
                        <?php endif; ?>
                    <?php echo $child->getLabel() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
</li>  
