<li <?php if ($this->page->isActive()){ echo ' class="nav-item active"'; }else{ echo ' class="nav-item"'; } ?> >
    <a 
        class="nav-link"
        href="<?php echo $this->page->getHref() ?>"
        <?php if ($this->page->getTarget() != ""): ?>
            target="<?php echo $this->page->getTarget(); ?>"
        <?php endif; ?>
        >
            <?php if ($this->page->get("icon") !== ""): ?>
            <i class="<?php echo $this->page->get("icon"); ?>"></i>
        <?php endif; ?>
        <?php echo $this->page->getLabel() ?>
    </a>
</li>
