<a class="btn btn-default" href="/user/profile">Profile</a>
<div class="clearfix"></div>

<div class="login-block">
    <div class="block block-transparent">


        <?php echo $this->form()->openTag($formManual) ?>
        <legend><?php echo $this->translate('Modificar Password'); ?></legend>

        <?php $element = $formManual->get('password'); ?>
        <div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
            <div class="input-group">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </div>
                <?php echo $this->formInput($element); ?>
            </div>


            <?php if ($this->formElementErrors($element)) : ?>
                <?php
                // Imprimo los errores
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<span class="help-block">')
                        ->setMessageSeparatorString('</span><span class="help-block">')
                        ->setMessageCloseString('</span>')
                        ->render($element);
                ?>
            <?php endif; ?>
        </div>


        <?php $element = $formManual->get('password_verify'); ?>
        <div  class="form-group<?php if ($this->formElementErrors($element)) echo " has-error" ?>">
            <div class="input-group">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </div>
                <?php echo $this->formInput($element); ?>
            </div>


            <?php if ($this->formElementErrors($element)) : ?>
                <?php
                // Imprimo los errores
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<span class="help-block">')
                        ->setMessageSeparatorString('</span><span class="help-block">')
                        ->setMessageCloseString('</span>')
                        ->render($element);
                ?>
            <?php endif; ?>
        </div>

        <div class="clearfix"></div>

        <?php echo $this->formElement($formManual->get('submit')); ?>


        <?php if ($formManual->getMessages()): ?>
            <?php foreach ($formManual->getMessages() as $msjs): ?>
                <?php foreach ($msjs as $key => $msj): ?>
                    <div class="alert alert-danger"><?php echo $msj; ?></div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php echo $this->form()->closeTag($formManual); ?>

    </div>


</div>

