<div class="clearfix"></div>

<div class="row ">
    <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-12">

        <div class="main-box  clearfix">

            <div class="main-box-header clearfix" >
                <h2 style="padding: 7px;"> <?php echo $this->translate('Modificar Password'); ?></h2>
            </div>


            <div class="main-box-body clearfix">



                <?php echo $this->form()->openTag($formManual) ?>

                <?php
                $element = $formManual->get('password');
                $element->setOption("addon", "fa fa-lock");
                ?>
                <?php echo $this->renderFormElement($element, "vertical"); ?>


                <?php
                $element = $formManual->get('password_verify');
                $element->setOption("addon", "fa fa-lock");
                ?>
                <?php echo $this->renderFormElement($element, "vertical"); ?>

                <div class="clearfix"></div>

                <?php
                $element = $formManual->get('submit');
                $element->setAttribute('class', 'btn btn-primary btnCustom pull-right');
                $element->setValue('Enviar');
                ?>

                <?php echo $this->renderFormElement($element, "vertical"); ?>
                <a class="pull-right btn btnCancelCustom" style="margin-right: 2px;" href="/user/profile"><?php echo $this->translate('Volver'); ?></a>

                <?php echo $this->form()->closeTag($formManual); ?>
            </div>



        </div>

    </div>     
</div>