<?php
if (!$this->element->getAttribute('placeholder') && $this->element->getLabel()) {
    $element->setAttribute('placeholder', $this->element->getLabel());
}
$element->setAttribute('style', "display:none;");
?>

<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <label class="btn btn-default fa fa-upload">
            <?php echo $this->formFile($this->element); ?>
        </label>

        <?php if ($element->getOption('description')): ?>
            <p class="bmd-help"><?php echo $this->element->getOption('description') ?></p>
        <?php endif; ?>

        <?php if ($this->formElementErrors($this->element)) : ?>
            <?php
            echo $this->formElementErrors()
                    ->setMessageOpenFormat('<span class="bmd-help">')
                    ->setMessageSeparatorString('</span><span class="bmd-help">')
                    ->setMessageCloseString('</span>')
                    ->render($this->element);
            ?>

        <?php endif; ?>

    </div>
</div>
