<?php
if (!$this->element->getAttribute('placeholder') && $this->element->getLabel()) {
    $element->setAttribute('placeholder', $this->element->getLabel());
}
?>

<div  class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">

    <?php echo $this->formElement($this->element); ?>

    <?php if ($element->getOption('description')): ?>
        <p class="bmd-help"><?php echo $this->element->getOption('description') ?></p>
    <?php endif; ?>

    <?php if ($this->formElementErrors($this->element)) : ?>
        <?php
        echo $this->formElementErrors()
                ->setMessageOpenFormat('<span class="bmd-help">')
                ->setMessageSeparatorString('</span><span class="bmd-help">')
                ->setMessageCloseString('</span>')
                ->render($this->element);
        ?>

    <?php endif; ?>

</div>