<!-- Le styles -->
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
->prependStylesheet($this->basePath('template/adminlte/custom/css/custom.css'))
->prependStylesheet($this->basePath('template/adminlte/dist/css/skins/_all-skins.min.css'))
->prependStylesheet($this->basePath('template/adminlte/dist/css/AdminLTE.css'))
->prependStylesheet($this->basePath('template/adminlte/bootstrap/css/bootstrap.min.css'))
->prependStylesheet($this->basePath('template/adminlte/ionicons/2.0.1/css/ionicons.min.css'))
->prependStylesheet($this->basePath('shared/font-awesome/css/font-awesome.min.css'))
;
?>

