<!-- Scripts -->
<?= $this->headScript()
->prependFile($this->basePath() . '/shared/global/js/CookieManager.js')
->prependFile($this->basePath('shared/adminlte/dist/js/app.js'))
->prependFile($this->basePath('shared/adminlte/bootstrap/js/bootstrap.min.js'))
->prependFile($this->basePath('shared/adminlte/plugins/jQuery/jquery-2.2.3.min.js'))
//->appendScript($this->partial('layout/js/layout.js'), 'text/javascript')
;
?>


