<!-- Scripts -->
<?= $this->headScript()
->prependFile($this->basePath() . 'template/adminlte/custom/js/CookieManager.js')
->prependFile($this->basePath('template/adminlte/dist/js/app.js'))
->prependFile($this->basePath('template/adminlte/bootstrap/js/bootstrap.min.js'))
->prependFile($this->basePath('template/adminlte/plugins/jQuery/jquery-2.2.3.min.js'))
//->appendScript($this->partial('layout/js/layout.js'), 'text/javascript')
;
?>


