<?php if ($user = $this->isAuthenticated()): ?>
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- Sidebar user panel -->
		<div class="user-panel">
			<div class="pull-left image">
			<?php if ($user->getImg()): ?>
				<img src="<?php echo $this->getSecurityOptions()->getProfilePicturePathRelative() . $user->getImg(); ?>" class="img-circle" alt="User Image">
				<?php else : ?>
            <img src="<?= $this->basePath('/img/user.jpg');?>" class="img-circle" alt="User Image">
        <?php endif; ?>
			</div>
			<div class="pull-left info">
				<p><?= $user->getName();?></p>

				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>
		<!-- search form 
		<form action="#" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="Search...">
				<span class="input-group-btn">
					<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
					</button>
				</span>
			</div>
		</form>
		-->
		<!-- /.search form -->
		<!-- sidebar menu: : style can be found in sidebar.less -->

		<!-- /.menu -->
		<?php
		$inicio = $this->
		navigation('default')
		->findOneByLabel('INICIO');

		echo $this->
		navigation($inicio)
		->menu()
		->setUlClass('nav nav-pills nav-stacked')
		->setPartial('zf-metal/commons/menu/vertical/nav-vertical');
		?>

	</section>
	<!-- /.sidebar -->
</aside>
<?php else: ?>
    <li class="pull-right">
        <a href="/user/login"><i><?php echo $this->translate('Iniciar Sesión'); ?> </i> <i class="glyphicon glyphicon-log-in"> </i></a>
    </li>
<?php endif; ?>