<?php $this->layout()->setTemplate('layout/layout_login') ?>
<?php
$this->notyFlash(true);
?>
<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">

        <div class="card card-login">
            <div class="card-header text-center" data-background-color="rose">
                <h4 class="card-title"><?php echo $this->layoutHelper()->getTitle(); ?></h4>
            </div>
            <div class="card-content">

                <p class="login-box-msg"><?= $this->translate('Register a new membership'); ?></p>

                <?php echo $this->form()->openTag($form) ?>
                <div class="form-group has-feedback">
                    <?php $element = $form->get('name')->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <?php $element = $form->get('email')->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <?php $element = $form->get('username')->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <?php $element = $form->get('password')->setAttribute('class', 'form-control'); ?>
                    <?php echo $this->formElement($element); ?>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">

                    <?php echo $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-primary btn-block btn-flat')->setAttribute('value', $this->translate('Register'))); ?>

                </div>
                <?php echo $this->form()->closeTag($form); ?>

                <a href="<?= $this->url('home'); ?>"
                   class="text-center"><?= $this->translate('I already have a membership'); ?></a>
            </div>

        </div>

    </div>

</div>