<div class="row">
    <div class="col-lg-3 col-md-4 col-xs-6 col-lg-offset-1 ">
        <a href="/admin/users">
            <div class="card card-chart" data-count="1">
                <div class="card-header" data-background-color="rose" data-header-animation="true">
                    <i class="material-icons cubeIcon">account_box</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Gestion de Usuarios</h4>
                </div>
            </div>
        </a>
    </div>


    <div class="col-lg-3 col-md-4 col-xs-6 ">
        <a href="/admin/roles">
            <div class="card card-chart" data-count="1">
                <div class="card-header" data-background-color="green" data-header-animation="true">
                    <i class="material-icons cubeIcon">all_out</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Gestion de Roles</h4>
                </div>
            </div>
        </a>
    </div>


    <div class="col-lg-3 col-md-4 col-xs-6 ">
        <a href="/admin/groups">
            <div class="card card-chart" data-count="1">
                <div class="card-header" data-background-color="blue" data-header-animation="true">
                    <i class="material-icons cubeIcon">group_work</i>
                </div>
                <div class="card-content">
                    <h4 class="card-title text-center">Gestion de Usuarios</h4>
                </div>
            </div>
        </a>
    </div>
</div>

<style>
    .cubeIcon {
        position: relative;
        text-align: center;
        width: 100%;
        font-size: 80px;
        margin-top: 15px;
        margin-bottom: 10px;
    }
</style>