<?php
$class = $this->element->getAttribute("class");
if (!preg_match("/form-control/", $class)) {
    $this->element->setAttribute("class", $class . " form-control");
}
?>

<div class="form-group<?php if ($this->formElementErrors($this->element)) echo " has-error" ?>">
    <div class="row label-on-left" style="margin-left: 0px;">
        <label class="control-label"><?php echo ucfirst($this->translate($this->element->getLabel())); ?></label>
    </div>
    <label class="btn btn-default glyphicon glyphicon-open">
        <?php echo $this->formElement($this->element); ?>
    </label>

    <?php if($this->element->getOption('description')):?>
    <p>
        <label class="control-label"><?php echo $this->element->getOption('description') ?></label>
    </p>
    <?php endif; ?>
    <?php if ($this->formElementErrors($this->element)) : ?>
        <?php
        echo $this->formElementErrors()
            ->setMessageOpenFormat('<span class="help-block">')
            ->setMessageSeparatorString('</span><span class="help-block">')
            ->setMessageCloseString('</span>')
            ->render($this->element);
        ?>

    <?php endif; ?>

</div>
