<?php $this->layout()->setTemplate('layout/layout_login') ?>
<?php echo $this->flash(); ?>

<div class="register-box">
  <div class="register-logo">
    <a href="<?= $this->url('home'); ?>"><b>BigBrother</b> 2</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Password Recovery</p>

    <?php echo $this->form()->openTag($form) ?>
      <div class="form-group has-feedback">
      <?php $element = $form->get('email'); ?>
      <?php echo $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <?php
                        echo $this->formElementErrors()
                                ->setMessageOpenFormat('<span class="help-block">')
                                ->setMessageSeparatorString('</span><span class="help-block">')
                                ->setMessageCloseString('</span>')
                                ->render($element);
                        ?>

                    <?php endif; ?>
        <span class="glyphicon glyphicon-user form-control-feedback"></span>
      </div>
     

      <div class="form-group has-feedback">
       <?php echo $this->formElement($form->get('submit')->setAttribute('class','btn btn-primary btn-block btn-flat')->setAttribute('value', $this->translate('Recovery'))); ?>
     </div>

    <?php echo $this->form()->closeTag($form); ?>

    <a href="<?= $this->url('home'); ?>" class="text-center">I already have a membership</a>
  </div>
  <!-- /.form-box -->
</div>
<!-- /.register-box -->
