<a class="btn btn-default" href="/admin/roles">Grilla Roles</a>
<div class="card">
    <div class="card-header card-header-icon" data-background-color="rose">
        <i class="material-icons">assignment</i>
    </div>
    <div class="card-content">
        <h4 class="card-title">Creando Rol</h4>
        <div class="clearfix"></div>
        <?php
        $groups = [
              [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'Role',
                'title' => "Role",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['name']
            ],
               [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'ChildrenRoles',
                'title' => "Children roles",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['children']
            ],
               [
                'type' => \ZfMetal\Commons\Options\FormGroupConfig::TYPE_HORIZONTAL,
                'id' => 'Permissions',
                'title' => "Permissions",
                'columns' => \ZfMetal\Commons\Consts::COLUMNS_ONE,
                'style' => \ZfMetal\Commons\Consts::STYLE_VERTICAL,
                'fields' => ['permissions']
            ],
        ];

        echo $this->renderForm($this->form, \ZfMetal\Commons\Consts::STYLE_VERTICAL, \ZfMetal\Commons\Consts::COLUMNS_ONE, $groups);
        ?>

    </div>

</div>

