<a class="btn btn-default" href="/admin/groups">Grilla Grupos</a>
<div class="card">
    <div class="card-header card-header-icon" data-background-color="rose">
        <i class="material-icons">assignment</i>
    </div>
    <div class="card-content">
        <h4 class="card-title">Detalle de Grupo</h4>
        <div class="clearfix"></div>

        <div class="col-lg-4 col-lg-offset-4 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12">
            <table class="table table-striped table-right">
                <tr>
                    <th class="text-right">Id:</th>
                    <td class="text-left"><?php echo $this->group->getId(); ?></td>
                </tr>

                <tr>
                    <th class="text-right">Nombre:</th>
                    <td class="text-left"><?php echo $this->group->getName(); ?></td>
                </tr>


                <tr>
                    <th class="text-right"><?php echo $this->translate('Usuarios'); ?></th>
                    <td class="text-left">
                        <ul>
                            <?php foreach ($this->group->getUsers() as $r): ?>
                                <li><?php echo $r->getName(); ?></li>

                            <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>


            </table>
        </div>
        <div class="col-lg-4">

        </div>

    </div>
</div>


