<?php $this->layout()->setTemplate('layout/layout_login') ?>
<?php
$this->notyFlash(true);
?>

<div class="login-box">
  <div class="login-logo">
    <a href="<?= $this->url('home')?>"><b>BigBrother</b> 2</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg"><?= $this->translate('Sign in to start your session')?></p>

    <?php echo $this->form()->openTag($form) ?>
    <div class="form-group has-feedback">
      <?php $element = $form->get('_username')->setAttribute('class','form-control'); ?>
      <?php echo $this->formElement($element); ?>
      <?php if ($element->getOption('description')): ?>
                   <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
             <?php endif; ?>
      <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    <div class="form-group has-feedback">
      <?php $element = $form->get('_password')->setAttribute('class','form-control'); ?>
      <?php
      echo $this->formElement($element);
      ?>
      <?php if ($element->getOption('description')): ?>
                   <p class="help-block"><?php echo $this->element->getOption('description') ?></p>
             <?php endif; ?>
      <span class="glyphicon glyphicon-lock form-control-feedback"></span>
    </div>

    <div class="row">
      <div class="col-xs-8">
        <?php if ($this->getSecurityOptions()->getRememberMe()) : ?>
          <div class="checkbox icheck">
            <label>
              <?php $element = $form->get('_remember'); ?>
              <?php
              echo $this->formElement($element);
              ?> <?= $this->translate('Remember Me');?>
            </label>
          </div>
        <?php endif; ?>
      </div>
      <!-- /.col -->
      <div class="col-xs-4">
       <?php echo $this->formElement($form->get('submit')->setAttribute('class','btn btn-primary btn-block btn-flat')->setAttribute('value',$this->translate('Sign In'))); ?>
     </div>
     <!-- /.col -->
   </div>
   <?php echo $this->form()->closeTag($form); ?>

   <a href="<?php echo $this->basePath('/user/recovery'); ?>"><?= $this->translate('I forgot my password')?></a><br>
   <?php if ($this->getSecurityOptions()->getPublicRegister()) : ?>
    <a href="<?php echo $this->basePath('/user/register'); ?>" class="text-center"><?= $this->translate('Register a new membership')?></a>
  <?php endif; ?>

  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

