<?php $this->layout()->setTemplate('layout/layout_login') ?>
<div class="row">
    <?php
    $this->notyFlash(true);
    ?>
</div>

<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
        <?php echo $this->form()->openTag($form) ?>
        <div class="card card-login">
            <div class="card-header text-center" data-background-color="gray">
                <div class="">
                    <?php echo $this->layoutHelper()->getTitle(); ?>
                </div>
            </div>

            <div class="card-content">


                <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">email</i>
                                            </span>
                    <div class="form-group label-floating is-empty">
                        <?php $element = $form->get('_username')->setAttribute('class', 'form-control')
                                                                ->setAttribute('placeholder', 'Usuario / Email'); ?>
                        <?php echo $this->formElement($element); ?>
                        <span class="material-input"></span>
                    </div>
                </div>
                <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">lock_outline</i>
                                            </span>
                    <div class="form-group label-floating is-empty">
                        <?php $element = $form->get('_password')->setAttribute('class', 'form-control')
                                                                ->setAttribute('placeholder', 'Clave'); ?>
                        <?php echo $this->formElement($element); ?>
                        <span class="material-input"></span>
                    </div>
                </div>


                <div class="togglebutton">
                    <label>
                        <?php $element = $form->get('_remember'); ?>
                        <?php echo $this->formElement($element); ?>
                        Recordar usuario
                    </label>
                </div>

            </div>
            <div class="footer text-center">
                <button type="submit" class="btn btn-rose btn-simple btn-wd btn-lg"> Ingresar</button>
            </div>

            <div class="footer text-center">
                <a href="<?php echo $this->basePath('/user/recovery'); ?>"><?= $this->translate('Recordar Contraseña') ?></a><br>
                <?php if ($this->getSecurityOptions()->getPublicRegister()) : ?>
                    <a href="<?php echo $this->basePath('/user/register'); ?>"
                       class="text-center"><?= $this->translate('Registrarse') ?></a>
                <?php endif; ?>
            </div>

        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>

