<?php $this->layout()->setTemplate('layout/layout_login') ?>
<?php
$this->notyFlash(true);
?>


<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
        <?php echo $this->form()->openTag($form) ?>
        <div class="card card-login">
            <div class="card-header text-center" data-background-color="rose">
                <h4 class="card-title">Login</h4>
                <div class="social-line">
                    <a href="#btn" class="btn btn-just-icon btn-simple">
                        <i class="fa fa-facebook-square"></i>
                    </a>
                    <a href="#pablo" class="btn btn-just-icon btn-simple">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#eugen" class="btn btn-just-icon btn-simple">
                        <i class="fa fa-google-plus"></i>
                    </a>
                </div>
            </div>
            <p class="category text-center">
                Or Be Classical
            </p>
            <div class="card-content">


                <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">email</i>
                                            </span>
                    <div class="form-group label-floating is-empty">
                        <?php $element = $form->get('_username')->setAttribute('class', 'form-control'); ?>
                        <?php echo $this->formElement($element); ?>
                        <span class="material-input"></span>
                    </div>
                </div>
                <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">lock_outline</i>
                                            </span>
                    <div class="form-group label-floating is-empty">
                        <?php $element = $form->get('_password')->setAttribute('class', 'form-control'); ?>
                        <?php echo $this->formElement($element); ?>
                        <span class="material-input"></span></div>
                </div>


                <div class="togglebutton">
                    <label>
                        <?php $element = $form->get('_remember'); ?>
                        <?php echo $this->formElement($element); ?>
                         Recordar usuario
                    </label>
                </div>

            </div>
            <div class="footer text-center">
                <button type="submit" class="btn btn-rose btn-simple btn-wd btn-lg"> Let's go</button>
            </div>

            <div class="footer text-center">
                <a href="<?php echo $this->basePath(' / user / recovery'); ?>"><?= $this->translate('I forgot my password') ?></a><br>
                <?php if ($this->getSecurityOptions()->getPublicRegister()) : ?>
                    <a href="<?php echo $this->basePath(' / user / register'); ?>"
                       class="text-center"><?= $this->translate('Register a new membership') ?></a>
                <?php endif; ?>
            </div>

        </div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>


