<?php echo $this->doctype(); ?>

<html lang="UTF-8">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <?php echo $this->headTitle($this->translate('TITLE'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->partial('layout/css'); ?>
        <?php echo $this->partial('layout/js'); ?>

    </head>
    <body>
        <?php echo $this->partial('layout/menu'); ?>

        <div class="main-content" >

            <?php echo $this->content; ?>

        </div> <!-- /container -->

        <?php //echo $this->partial('layout/footer'); ?>


        <?php echo $this->inlineScript() ?>
    </body>
</html>
