<nav class="navbar navbar-expand-md  navbar-light bg-light  justify-content-between fixed-top">

    <a class="navbar-brand mr-0 mr-md-2" href="/">
       <?php echo $this->layoutHelper()->getTitle(); ?>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <?= $this->renderMenu(null,null,"navbar-nav mr-auto"); ?>

        <?= $this->partial('zf-metal/security/menu/menu'); ?>
    </div>





</nav>